FROM python:latest

RUN ["mkdir","/var/application"]
WORKDIR /var/application
COPY application .
COPY requirements.txt .
RUN ["pip","install","-r","requirements.txt"]
EXPOSE 5000/tcp
CMD ["flask","run","--host","0.0.0.0"]